name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      stack:
        description: 'Stage'
        required: true
        default: 'qa'
      reason:
        description: 'Reason'
        required: false
        default: ''
  push:
    branches:
      - "master"
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    steps:
    - name: 'Test'
      run: echo "$GITHUB_EVENT_NAME"
