name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      stack:
        description: 'Stage'
        required: true
        default: 'qa'
      reason:
        description: 'Reason'
        required: false
        default: ''
  push:
    branches:
      - master
  release:
    types: # This configuration does not affect the page_build event above
      - created

env:
  version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || (github.event_name == 'release' && github.event.release.name || github.event.head_commit.id ) }}
  name: ${{ github.event_name == 'workflow_dispatch' && 'workflow_dispatch' || (github.event_name == 'release' && 'release' || 'push') }}
  stack: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.stack || (github.event_name == 'release' && 'qa' || 'prod') }}
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: 'head commit'
      env:
        head_commit: ${{ github.event.head_commit.id }}
      run: echo "$head_commit"
    - name: 'version'
      run: echo "$version"
    - name: 'Test'
      run: echo "$stack"
