name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      stack:
        description: 'Stage'
        required: true
        default: 'qa'
      reason:
        description: 'Reason'
        required: false
        default: ''
  push:
    branches:
      - master
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - name: 'Test'
      run: echo "$GITHUB_EVENT_NAME"
